apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          env:
            - name: NATS_URL
              value: "{{ .Values.auth.env.NATS_URL }}"
            - name: MONGODB_URI
              value: "mongodb://{{ .Release.Name }}-auth-mongodb:{{ .Values.mongodb.auth.service.port }}/{{ .Values.mongodb.auth.database }}"
            - name: JWT_SECRET  
              value: "{{ .Values.auth.env.JWT_SECRET }}" 
          ports:
            - containerPort: {{ .Values.auth.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
  selector:
    app: auth
