{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-auth
                port:
                  number: {{ .Values.auth.service.port }}
          - path: /api/catalog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-catalog
                port:
                  number: {{ .Values.catalog.service.port }}
          - path: /api/orders(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-orders
                port:
                  number: {{ .Values.orders.service.port }}
          - path: /api/prices(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prices
                port:
                  number: {{ .Values.prices.service.port }}
{{- end }}
