{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "/"
    nginx.ingress.kubernetes.io/use-http2: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    # Main application host
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-auth
                port:
                  number: {{ .Values.auth.service.port }}
          - path: /api/catalog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-catalog
                port:
                  number: {{ .Values.catalog.service.port }}
          - path: /api/orders(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-orders
                port:
                  number: {{ .Values.orders.service.port }}
          - path: /api/prices(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prices
                port:
                  number: {{ .Values.prices.service.port }}

    # Separate host for the admin subdomain
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port:
                  number: {{ .Values.admin.service.port }}
{{- end }}
